services:
  strava_kudos:
    image: ghcr.io/aexel90/strava_kudos:main
    container_name: strava_kudos
    restart: on-failure:2
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./.env:/app/.env:ro
  strava_kudos_local:
    image: strava_kudos_local
    build: .
    container_name: strava_kudos_local
    restart: on-failure:2
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./.env:/app/.env:ro